### ISSUE TITLE
Spacing between "Projects"-Label and "Create New Project"-Button

### ISSUE THREAD

**Issue by haukebruno** [TimPietrusky/mantisbt-is-a-rockstar#1]
It would be nice, if the button is a little bit more right in the layout.

My screen resolution: 1366*768

See http://imgur.com/IZIN8

**Comment by TimPietrusky** [comment]
Added some space between "Projects"-Label and "Create New Project"-Button.

Fixed in master.

**Comment by haukebruno** [comment]
works for me,

Thx
Hauke

---

original message
timestamp: Thursday 07 June 2012 13:50:26
from: Tim Pietrusky 
reply@reply.github.com
to: Hauke Bruno oss@haukebruno.de
cc:  
message id: <TimPietrusky/mantisbt-is-a-rockstar/issues/1/6187583@github.com>

> Added some space between "Projects"-Label and "Create New Project"-Button.
> 
> Fixed in master.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/TimPietrusky/mantisbt-is-a-rockstar/issues/1#issuecomment
> -6187583

---
