### ISSUE TITLE
Enhance installation, don't overwrite existing files

### ISSUE THREAD

**Issue by atrol** [TimPietrusky/mantisbt-is-a-rockstar#5]
The installation instruction says:
Copy all files from the unpacked folder css/\* to <mantis_root>/css/

Please don't tell users to overwrite any original MantisBT file!

a) They might get problems or unnecessary work when updating.
b) It might become hard for the MantisBT support when dealing with issues which are caused by your theme.

A better approach for such kind of customization is to use a separate directory.
You can add the following line to file config_inc.php to separate the customization from the original installation.
$g_css_include_file = "<PathToMyCustomizations>/css/default.css";

**Comment by TimPietrusky** [comment]
You are right. I will update the installation instruction.

**Comment by TimPietrusky** [comment]
Thank you for your help.
